// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'data': String,
    'dataurl': String,
    'field1': String,
    'field2': String,
    'field3': String,
    'formid': Number,
    'image': String,
    'isActive': Number,
    'mainmenu': String,
    'menuID': String,
    'menuName': String,
    'points': Number,
    'url': String,
  }, {
    timestamps: false,
  });

  return mongoose.model('submenus', schema, 'submenus');
};
