// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'Date': Date,
    'account': String,
    'addType': String,
    'address': String,
    'adressproof': String,
    'balance': Number,
    'bank': String,
    'email': String,
    'idType': String,
    'idproof': String,
    'ifsc': String,
    'isActive': Number,
    'name': String,
    'paid': Number,
    'parent': String,
    'password': String,
    'pending': Number,
    'phone': String,
    'photo': String,
    'points': Number,
    'role': String,
    'signature': String,
    'target': Number,
  }, {
    timestamps: false,
  });

  return mongoose.model('users', schema, 'users');
};
